### ISSUE TITLE
possible feature: Support a limit on the number of rrdp serials that is kept around

### ISSUE THREAD

**Issue by ties** [NLnetLabs/krill-sync#22]
As a repository operator, I want to keep my rsync directories around for a long time because the initial sync has been observed to be very slow for connections with low bandwidth and high RTT. However, at the same time, a repository operator may want to have an upper bound on the number of copies stored.

If the cleanup process is being refactored it may be nice to support this use case.

Based on rfc 8181 [rrdp repos need to publish at least every minute](https://datatracker.ietf.org/doc/html/rfc8182) if objects arrive. Because of this a public publication service can be compelled to publish at least 60 deltas per hour.
```
3.3.2.  Publishing Updates

   Whenever the Repository Server receives updates from a Certificate
   Authority, it MUST generate new snapshot and Delta Files within one
   minute.  If a Repository Server services a large number of
   Certificate Authorities, it MAY choose to combine updates from
   multiple CAs.  If a Repository Server combines updates in this way,
   it MUST ensure that publication never postponed for longer than one
   minute for any of the CAs involved.
``` 

In practice we see reasonably large repositories publish many more copies 
<img width="1278" alt="Screenshot 2021-05-21 at 08 22 24" src="https://user-images.githubusercontent.com/199058/119092292-8b0b1580-ba0e-11eb-9096-5cc34dca448c.png">

If the cleanup process is being refactored it may be good to limit the number of copies stored (or limit it on the side of krill).

**Comment by timbru** [comment]
Generally speaking I think the actual back-end server should be the one doing the smartness.. We build quite an elaborate strategy into krill 0.9 for this.

That said I do see a use case for allowing an optional hard upper limit for the number of deltas that krill-sync will include. Especially where upgrades of a back-end server may be more involved.

As per RRDP RFC 8182 the worst that could happen is that an RP needs to do a full sync based on the latest snapshot.

**Comment by ties** [comment]
I agree that the backend server should contain the smartness and contains what the repository operator indents to publish. And for rsync this is easy.

However with RRDP things get harder. We want a directory that exists to stay around until the time limit hits - clients may still be transferring it. In practice, we do see some clients not finishing their transfer within two hours (when the repository copy is deleted).

For a public repository, a user can force the repository to write a delta every minute. Or more often for a repository that does not batch over all CAs. In that case it may be nice to control the number of rsync repositories stored.

So:
  * For RRDP I think the backend server shows the intent of what the repository operator intends to publish
  * For rsync I'm hesitant about the number (and size of the) files that writing all revisions in the period entails.

I ended up sizing a machine so that it could store 120+ copies, disk space is cheaper than developer time :)
