### ISSUE TITLE
be session-aware

### ISSUE THREAD

**Issue by ties** [NLnetLabs/krill-sync#23]
As a repository operator I want krill-sync to be aware of the RRDP session so that it cooperates better with a non-krill publication service.

Specifically: Handle this correctly in cleanup, and probably store the RRDP `session_id` somehow as well instead of just `serial`. I would not mind some metadata per directory.

**Comment by timbru** [comment]
I believe this is resolved in 0.2-dev. Cleanup is done when a directory (for a specific session and serial) has been deprecated for longer than X seconds (10 minutes default). It's the same time for deprecated RRDP files and rsync dir - but it can just be set to 1 hour or something if 10 minutes would really be too quick still.
