### ISSUE TITLE
Do not store full XML files in memory

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill-sync#27]
Memory usage could be improved by not keeping the XML in memory - just write it disk and forget it.

The downside is that krill-sync will not be able to regenerate the XML files on disk if they were manually deleted. But, this is unlikely to be an issue.

**Comment by ximon18** [comment]
To be clear, this relates to your dev branch right, not to released krill-sync?

**Comment by timbru** [comment]
Indeed! Added it to the 0.2 project as wel..
