### ISSUE TITLE
Lock file test & create should be atomic

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill-sync#31]
The code in `fn lock()` is not atomic, it first tests if the PID file exists then writes to it, but this isn't safe if two krill-sync processes start at exactly the same time. Perhaps it should read back the PID after writing it to see if it is for the current PID, or the file should be written to a temporary location then atomically moved or ...?

**Comment by timbru** [comment]
This is not a new problem :) It affects 0.1.x as well as 0.2-dev.

That said, it is not a new problem, and it seems someone made a nice solution:
https://crates.io/crates/fslock

So, perhaps just use that?
