### ISSUE TITLE
Preserve original XML files and use less memory

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill-sync#36]
Currently krill-sync parses the source RRDP files to build up an internal state to which deltas may be applied.

The advantage of this approach is that it's easy to follow and test the code path.

The disadvantage is that the files are kept in memory and re-serialized to XML when writing them to disk. This means that memory usage can be high (up to 2GB for rrdp.ripe.net) and the snapshot and delta files are reformatted.

A better, but more complicated, approach could be to download files straight to disk, e.g. using:
https://docs.rs/reqwest/0.11.4/reqwest/blocking/struct.Response.html#method.copy_to

And rather than basing the current files on applying parsed deltas to current state, also download any new snapshot file this way.

Then, when writing rsync files parse the latest RRDP snapshot file from local disk, implementing `ParseSnapshot` from rpki-rs, and rather than adding parsed files to a structure in memory write them straight to disk:
https://github.com/NLnetLabs/rpki-rs/blob/f0006134f918bbdbde833ba665d0bd71c4f167b3/src/rrdp.rs#L654

We should still set the mtime for files in the rsync repositories based on when they were created to avoid that certain clients would do full re-syncs. Currently we keep the 'since' time in the state which means that we can fall back to when a file was first seen in case it cannot be parsed. If we change the behaviour as described above we would either need to keep an additional structure to keep the mapping, or accept that we just don't modify the mtime for files that we cannot parse. They should be few and far between - we may even never see them..

**Comment by timbru** [comment]
Changed were made after creating this issue, and snapshot and delta files are preserved as fetched. The notification file is parsed and re-written but this is hard to avoid because krill-sync may need to tweak the notification file - e.g. change the number of deltas.

The remaining issue memory use. State is kept in memory, but also files are read into memory first and then written.

It is not clear to me whether this is a real issue for any users. It can be fixed as described above but it's a non-trivial change. So, in short closing this for the time being. It can be re-opened if needed.

@ties any concerns?

**Comment by ties** [comment]
> It is not clear to me whether this is a real issue for any users. It can be fixed as described above but it's a non-trivial change. So, in short closing this for the time being. It can be re-opened if needed.
> 
> @ties any concerns?

Memory usage is not a concern, I agree with this choice. Optimizing for memory usage by streaming does not feel worth it.
