### ISSUE TITLE
Use krill-sync to warm a cache

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill-sync#44]
An idea..

If operators simply use something like NGINX as a caching server then load balancing becomes easier. In particular: no more sticky sessions would be needed: get notification.xml from node A, fetch delta from node B -> cache miss -> node B gets it just in time.

The downside however is cold caches with regards to snapshot/delta files in case the back-end goes down.

So, a possible idea is to use krill-sync or some other simple script to get the notification file and all files mentioned in it from a caching https server regularly. They can be promptly forgotten but should just trigger that the cache gets missing files. This can be done at low cost - so there should be no issue running this every couple of seconds even on localhost..

This will also allow graceful shutdown of the publication server (not implemented yet) -> i.e. tell the publication server to stop accepting updates but serve the RRDP files. Then after, say 10 seconds, shut it down for maintenance/upgrades.

**Comment by ties** [comment]
I like the idea of the graceful shutdown but I do not like the risk for downtime that such a setup still has (backend goes down or connectivity goes down -> cache period of `notification.xml` expires -> 404s there).

I would rather avoid the need for sticky sessions by waiting before writing the notification.xml. I think that is safe and covers the case of the backend going down:

## 
  * Node A runs krill-sync, fetches all the files, does not write notification.xml yet, waits for `t_notification` before writing `notification.xml`
  * Node B runs krill-sync (within `t_notification`), fetches all the files and writes them, waits `t_notification`. 

If a client then fetches the notification.xml from node A before node B runs, it does not reference any files not present yet. So in the scenario where `notification.xml` is fetched from node A, all other files from node B, the files referenced already exist. And as long as `t_notification` is smaller than the update interval of RPs it is not visible to RPs - this delay can probably be up to 5 minutes in practice.

#### Caveat
In this scenario, if either node stops updating, a problem exists. To handle failures of the backend [and have health checks] you likely need some consensus protocols that can determine the state of the cluster.

**Comment by timbru** [comment]
> I like the idea of the graceful shutdown but I do not like the risk for downtime that such a setup still has (backend goes down or connectivity goes down -> cache period of `notification.xml` expires -> 404s there).

Serve stale. Example nginx config:

```
# Use nginx as a cache for the back-end server.
proxy_cache_path /var/lib/nginx-cache 
   levels=1:2 
   keys_zone=my_cache:1m
   max_size=1g
   use_temp_path=off;

server {

  server_name rrdp.accept.krill.cloud;

  location / {
     proxy_cache my_cache;
     proxy_cache_use_stale 
        error timeout http_500 http_502 http_503 http_504;

     proxy_pass https://ps.accept.krill.cloud/rrdp/;
  }
}
```

This ensures that local stale copies are served if they would expire.

There is another issue though.. if you keep querying localhost for an update notification file it may not have expired on your node, while it has already expired on another node. So to do this properly you should query the origin, and be a sport: use etag/if-modified-since - if there is an update then query any new files from localhost and perhaps instruct the cache to re-refetch the notification file as well.

How safe this is has a strong correlation with the update frequency of the back-end publication server. If you are operating your own own server for one or a hand full of CA then it is unlikely that one of your nodes would be able to update, while the other could not. Not impossible, but you would have to have a crash of the back-end within seconds after writing an update. For small organisations these are usually hours apart.

So, yes, all in all this is not perfect. But it is a relatively simple and pretty safe approach nonetheless.

> 
> I would rather avoid the need for sticky sessions by waiting before writing the notification.xml. I think that is safe and covers the case of the backend going down:
> 
> * Node A runs krill-sync, fetches all the files, does not write notification.xml yet, waits for `t_notification` before writing `notification.xml`
> * Node B runs krill-sync (within `t_notification`), fetches all the files and writes them, waits `t_notification`.
> 
> If a client then fetches the notification.xml from node A before node B runs, it does not reference any files not present yet. So in the scenario where `notification.xml` is fetched from node A, all other files from node B, the files referenced already exist. And as long as `t_notification` is smaller than the update interval of RPs it is not visible to RPs - this delay can probably be up to 5 minutes in practice.

Yeah I know we discussed this earlier.

Downside is that you need to synchronize the fetches in this case, and know how long they take as a maximum. You could make the interval very long, but then you are adding more delays for everyone. ROV timing is still being discussed but I hear noises from operators that they want to have fixes for mistakenly issued ROAs out into routers in around 15 minutes, so adding 5 minutes is significant.

> 
> #### Caveat
> In this scenario, if either node stops updating, a problem exists. 

Furthermore.. the nodes don't know if the other node got a failure. There is still a race condition where node A fetches everything just fine, waits before writing its new notification file, but node B was not able to sync and does not update. I.e. the not updating can easily be caused by the back-end going down rather than a node.

> To handle failures of the backend [and have health checks] you likely need some consensus protocols that can determine the state of the cluster.

I am really not convinced that I would want to go here at all, consensus I mean. Yes, ultimately that may be a solution for consistency in a distributed system, but obviously this adds a great deal of complexity.

But, a poor man's consensus could consist of detecting that the back-end is unavailable and in such cases query other nodes to see if they have any newer state. Still complex - needs thought.. might be a useful future addition.

**Comment by ties** [comment]
> Serve stale. Example nginx config:

Really good one.
> Yeah I know we discussed this earlier.

I know - I just wanted this to be out there somewhere in a public location as well instead of just in private conversation :).

> I am really not convinced that I would want to go here at all, consensus I mean. Yes, ultimately that may be a solution for consistency in a distributed system, but obviously this adds a great deal of complexity.
> 
> But, a poor man's consensus could consist of detecting that the back-end is unavailable and in such cases query other nodes to see if they have any newer state. Still complex - needs thought.. might be a useful future addition.

I'm also on the fence about it. It could also be included in a wrapper that orchestrates `krill-sync` runs. At least formal distributed systems knowledge is a good topic for me to spend education budget on since I have some left 😅
