### ISSUE TITLE
rsync current link target not created for empty repository

### ISSUE THREAD

**Issue by bjpbakker** [NLnetLabs/krill-sync#62]
When setting up a new test environment we noticed that having a fresh repository with an empty snapshot (i.e. no ROAs) causes krill-sync to not create the rsync session directory.

As a result of this, the `current` symlink is created with a non-existing target and rsync breaks because it cannot chdir.

The expected behavior would be to create the session directory without any content, so that clients can "sync" the empty repository with rsync.

We observed this behavior with krill-sync 0.2.1-rc2.

**Comment by timbru** [comment]
Ah yes, I agree that it should create an empty directory in this case. Added to my to-do list.

**Comment by timbru** [comment]
Should work now, released in 0.2.1-rc3
